elastic-search:
  host: "localhost"
  port: "3000"
  basepath: "/acme-elasticsearch-v1"
  resources:
    products: "/products"

big-company-db:
  host: "localhost"
  port: "3000"
  basepath: "/acme-bigcompanydb-v1"
  resources:
    products: "/products"

mongo-db:
  host: "localhost"
  port: "3000"
  basepath: "/acme-mongodb-v1"
  resources:
    products: "/products"

email:
  host: "localhost"
  port: "3000"
  basepath: "/acme-emailnotification-v1"
  resources:
    send: "/send"

acme-products-queue:
  name: "acme-product-queue"
  host: "https://mq-us-east-1.anypoint.mulesoft.com/api/v1"
  client: "709d7b2688384b23a1453ce3b692496e"
  secret: "8162BAD7Ba2048aC81D9b74beE5A2867"
  